# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.gen/sources_1/bd/system_wrapper/ip/system_wrapper_debug_bridge_0_0/bd_0/ip/ip_1/constraints/bsip.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_07e0_bsip_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.gen/sources_1/bd/system_wrapper/ip/system_wrapper_debug_bridge_0_0/bd_0/ip/ip_1/bd_07e0_bsip_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_07e0_bsip_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.gen/sources_1/bd/system_wrapper/ip/system_wrapper_debug_bridge_0_0/bd_0/ip/ip_1/constraints/bsip.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_07e0_bsip_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.gen/sources_1/bd/system_wrapper/ip/system_wrapper_debug_bridge_0_0/bd_0/ip/ip_1/bd_07e0_bsip_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_07e0_bsip_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
