# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.srcs/sources_1/bd/system_wrapper/ip/system_wrapper_axi_bram_ctrl_1_0/system_wrapper_axi_bram_ctrl_1_0.xci
# IP: The module: 'system_wrapper_axi_bram_ctrl_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.gen/sources_1/bd/system_wrapper/ip/system_wrapper_axi_bram_ctrl_1_0/system_wrapper_axi_bram_ctrl_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_wrapper_axi_bram_ctrl_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.srcs/sources_1/bd/system_wrapper/ip/system_wrapper_axi_bram_ctrl_1_0/system_wrapper_axi_bram_ctrl_1_0.xci
# IP: The module: 'system_wrapper_axi_bram_ctrl_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.gen/sources_1/bd/system_wrapper/ip/system_wrapper_axi_bram_ctrl_1_0/system_wrapper_axi_bram_ctrl_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_wrapper_axi_bram_ctrl_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
