# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-272457-idris-HP-EliteBook-840-G3/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z010clg400-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.gen/sources_1/bd/system_wrapper/ipshared/f0b6/hdl/verilog
    /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.gen/sources_1/bd/system_wrapper/ipshared/35de/hdl/verilog
    /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.gen/sources_1/bd/system_wrapper/ipshared/c2c6
  } {
      /home/idris/opt/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /home/idris/opt/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      /home/idris/opt/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -sv -include {
    /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.gen/sources_1/bd/system_wrapper/ipshared/f0b6/hdl/verilog
    /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.gen/sources_1/bd/system_wrapper/ipshared/35de/hdl/verilog
    /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.gen/sources_1/bd/system_wrapper/ipshared/c2c6
  } {
      /home/idris/projects/FPGA_VISION/NN_SHIFT/src/common/arbiter.sv
      /home/idris/projects/FPGA_VISION/NN_SHIFT/src/bram/bram_dp.sv
      /home/idris/projects/FPGA_VISION/NN_SHIFT/src/convolution/convo_2d.sv
      /home/idris/projects/FPGA_VISION/NN_SHIFT/src/convolution/convo_2d_wrapper.sv
      /home/idris/projects/FPGA_VISION/NN_SHIFT/src/maths/mul.sv
      /home/idris/projects/FPGA_VISION/NN_SHIFT/src/common/mult_mux.sv
      /home/idris/projects/FPGA_VISION/NN_SHIFT/src/common/ram_mux.sv
      /home/idris/projects/FPGA_VISION/NN_SHIFT/src/utils/ram_switch.sv
      /home/idris/projects/FPGA_VISION/NN_SHIFT/top/conv_2d_top.sv
    }
      rt::read_verilog -include {
    /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.gen/sources_1/bd/system_wrapper/ipshared/f0b6/hdl/verilog
    /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.gen/sources_1/bd/system_wrapper/ipshared/35de/hdl/verilog
    /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.gen/sources_1/bd/system_wrapper/ipshared/c2c6
  } {
      ./.Xil/Vivado-272457-idris-HP-EliteBook-840-G3/realtime/system_wrapper_processing_system7_0_0_stub.v
      ./.Xil/Vivado-272457-idris-HP-EliteBook-840-G3/realtime/system_wrapper_debug_bridge_0_0_stub.v
      ./.Xil/Vivado-272457-idris-HP-EliteBook-840-G3/realtime/bd_07e0_axi_jtag_0_stub.v
      ./.Xil/Vivado-272457-idris-HP-EliteBook-840-G3/realtime/bd_07e0_bsip_0_stub.v
      ./.Xil/Vivado-272457-idris-HP-EliteBook-840-G3/realtime/system_wrapper_axi_gpio_0_0_stub.v
      ./.Xil/Vivado-272457-idris-HP-EliteBook-840-G3/realtime/system_wrapper_axi_gpio_0_1_stub.v
      ./.Xil/Vivado-272457-idris-HP-EliteBook-840-G3/realtime/system_wrapper_axi_smc_0_stub.v
      ./.Xil/Vivado-272457-idris-HP-EliteBook-840-G3/realtime/system_wrapper_rst_ps7_0_50M_0_stub.v
      ./.Xil/Vivado-272457-idris-HP-EliteBook-840-G3/realtime/system_wrapper_axi_bram_ctrl_0_1_stub.v
      ./.Xil/Vivado-272457-idris-HP-EliteBook-840-G3/realtime/system_wrapper_axi_bram_ctrl_1_0_stub.v
      ./.Xil/Vivado-272457-idris-HP-EliteBook-840-G3/realtime/system_wrapper_clk_wiz_0_0_stub.v
      /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.gen/sources_1/bd/system_wrapper/synth/system_wrapper.v
      /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.gen/sources_1/bd/system_wrapper/hdl/system_wrapper_wrapper.v
    }
      rt::read_vhdl -lib xpm /home/idris/opt/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top conv_2d_top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-272457-idris-HP-EliteBook-840-G3/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
