# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system_wrapper/system_wrapper.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_wrapper || ORIG_REF_NAME==system_wrapper} -quiet] -quiet

# IP: bd/system_wrapper/ip/system_wrapper_processing_system7_0_0/system_wrapper_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_wrapper_processing_system7_0_0 || ORIG_REF_NAME==system_wrapper_processing_system7_0_0} -quiet] -quiet

# IP: bd/system_wrapper/ip/system_wrapper_debug_bridge_0_0/system_wrapper_debug_bridge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_wrapper_debug_bridge_0_0 || ORIG_REF_NAME==system_wrapper_debug_bridge_0_0} -quiet] -quiet

# IP: bd/system_wrapper/ip/system_wrapper_axi_gpio_0_0/system_wrapper_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_wrapper_axi_gpio_0_0 || ORIG_REF_NAME==system_wrapper_axi_gpio_0_0} -quiet] -quiet

# IP: bd/system_wrapper/ip/system_wrapper_axi_gpio_0_1/system_wrapper_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_wrapper_axi_gpio_0_1 || ORIG_REF_NAME==system_wrapper_axi_gpio_0_1} -quiet] -quiet

# IP: bd/system_wrapper/ip/system_wrapper_axi_smc_0/system_wrapper_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_wrapper_axi_smc_0 || ORIG_REF_NAME==system_wrapper_axi_smc_0} -quiet] -quiet

# IP: bd/system_wrapper/ip/system_wrapper_rst_ps7_0_50M_0/system_wrapper_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_wrapper_rst_ps7_0_50M_0 || ORIG_REF_NAME==system_wrapper_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/system_wrapper/ip/system_wrapper_axi_bram_ctrl_0_1/system_wrapper_axi_bram_ctrl_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_wrapper_axi_bram_ctrl_0_1 || ORIG_REF_NAME==system_wrapper_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/system_wrapper/ip/system_wrapper_axi_bram_ctrl_1_0/system_wrapper_axi_bram_ctrl_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_wrapper_axi_bram_ctrl_1_0 || ORIG_REF_NAME==system_wrapper_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/system_wrapper/ip/system_wrapper_clk_wiz_0_0/system_wrapper_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_wrapper_clk_wiz_0_0 || ORIG_REF_NAME==system_wrapper_clk_wiz_0_0} -quiet] -quiet

# XDC: /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.gen/sources_1/bd/system_wrapper/system_wrapper_ooc.xdc
