# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.srcs/sources_1/bd/system_wrapper/ip/system_wrapper_debug_bridge_0_0/system_wrapper_debug_bridge_0_0.xci
# IP: The module: 'system_wrapper_debug_bridge_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.gen/sources_1/bd/system_wrapper/ip/system_wrapper_debug_bridge_0_0/bd_0/bd_07e0.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_07e0 || ORIG_REF_NAME==bd_07e0} -quiet] -quiet

# IP: /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.gen/sources_1/bd/system_wrapper/ip/system_wrapper_debug_bridge_0_0/bd_0/ip/ip_0/bd_07e0_axi_jtag_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_07e0_axi_jtag_0 || ORIG_REF_NAME==bd_07e0_axi_jtag_0} -quiet] -quiet

# IP: /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.gen/sources_1/bd/system_wrapper/ip/system_wrapper_debug_bridge_0_0/bd_0/ip/ip_1/bd_07e0_bsip_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_07e0_bsip_0 || ORIG_REF_NAME==bd_07e0_bsip_0} -quiet] -quiet

# XDC: /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.gen/sources_1/bd/system_wrapper/ip/system_wrapper_debug_bridge_0_0/bd_0/bd_07e0_ooc.xdc

# XDC: /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.gen/sources_1/bd/system_wrapper/ip/system_wrapper_debug_bridge_0_0/system_wrapper_debug_bridge_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_wrapper_debug_bridge_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.srcs/sources_1/bd/system_wrapper/ip/system_wrapper_debug_bridge_0_0/system_wrapper_debug_bridge_0_0.xci
# IP: The module: 'system_wrapper_debug_bridge_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.gen/sources_1/bd/system_wrapper/ip/system_wrapper_debug_bridge_0_0/bd_0/bd_07e0.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_07e0 || ORIG_REF_NAME==bd_07e0} -quiet] -quiet

# IP: /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.gen/sources_1/bd/system_wrapper/ip/system_wrapper_debug_bridge_0_0/bd_0/ip/ip_0/bd_07e0_axi_jtag_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_07e0_axi_jtag_0 || ORIG_REF_NAME==bd_07e0_axi_jtag_0} -quiet] -quiet

# IP: /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.gen/sources_1/bd/system_wrapper/ip/system_wrapper_debug_bridge_0_0/bd_0/ip/ip_1/bd_07e0_bsip_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_07e0_bsip_0 || ORIG_REF_NAME==bd_07e0_bsip_0} -quiet] -quiet

# XDC: /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.gen/sources_1/bd/system_wrapper/ip/system_wrapper_debug_bridge_0_0/bd_0/bd_07e0_ooc.xdc

# XDC: /home/idris/projects/FPGA_VISION/NN_SHIFT/hardware/convo_2d/convo_2d.gen/sources_1/bd/system_wrapper/ip/system_wrapper_debug_bridge_0_0/system_wrapper_debug_bridge_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_wrapper_debug_bridge_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
